sudo: false
language: python
python: 3.5
env:
  - TOXENV=py27-pandas15
  - TOXENV=py27-pandas16
  - TOXENV=py27-pandas17

  - TOXENV=py34-pandas15
  - TOXENV=py34-pandas16
  - TOXENV=py34-pandas17

  - TOXENV=py35-pandas15
  - TOXENV=py35-pandas16
  - TOXENV=py35-pandas17

  - TOXENV=flake8

install:
  - pip install tox
script:
  - travis_retry tox

