name: Publish distributions to PyPI or TestPyPI

on:
  release:
    types:
      - published

jobs:
  pypi-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install twine
      run: |
        python -m pip install -U pip
        python -m pip install -U twine wheel build

    - name: Build the distributions
      run: |
        python -m build --sdist --wheel

    - name: Verify the distributions
      run: twine check dist/*

    - name: Publish distribution to PyPI
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
